#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping-cart?serverTimezone=UTC
    username: root
    password: Sumit@1998
    driver-class-name: com.mysql.cj.jdbc.Driver
---
# Hibernate JPA Configuration
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
